---
- name: Break nginx app index file
  hosts: demo-app-nginx
  become: true
  gather_facts: false
  tasks:
    - name: Rename index.html so it can't be found
      ansible.builtin.command: mv /usr/share/nginx/html/index.html /usr/share/nginx/html/index.html.bak

    - name: Reload nginx to apply changes
      ansible.builtin.service:
        name: nginx
        state: reloaded
