---
- name: Break nginx app
  hosts: demo-app-nginx
  become: true
  gather_facts: false
  tasks:
    - name: Backup nginx site config (if exists)
      ansible.builtin.copy:
        src: /etc/nginx/nginx.conf
        dest: /etc/nginx/nginx.conf.bak
        remote_src: true
      ignore_errors: true

    - name: Intentionally change index to a non-existent file
      ansible.builtin.replace:
        path: /etc/nginx/nginx.conf
        regexp: 'index\s+index\.html;'
        replace: 'index missing.html;'

    - name: Reload nginx to apply changes
      ansible.builtin.service:
        name: nginx
        state: reloaded