---
- name: Corrupt nginx config to trigger a specific error
  hosts: demo3.sandbox566.opentlc.com
  become: true
  tasks:

    - name: Inject invalid directive into nginx config
      ansible.builtin.replace:
        path: /etc/nginx/nginx.conf
        regexp: 'events \{[^\}]*\}'
        replace: |
          events {
              worker_connections 1024;
              other true;
          }

    - name: Reload nginx to apply changes
      ansible.builtin.service:
        name: nginx
        state: reloaded