---
- name: Break nginx app
  hosts: demo-app-nginx
  become: true
  gather_facts: false
  tasks:
    # Simulation: Somebody has put an invalid cert on the server when rotating certs.
    - name: Replace TLS key with invalid file
      ansible.builtin.copy:
        dest: /etc/nginx/ssl/server.key
        content: "this-is-not-a-valid-key"
        mode: '0600'

    - name: Reload nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
      ignore_errors: true
