---
- name: Check nginx app health and run diagnostics if unavailable
  hosts: all
  execution_strategy: parallel
  sources:
    - ansible.eda.url_check:
        urls:
          - https://demo3.sandbox566.opentlc.com/
          # You could list lots of application URLS to watch here
        delay: 300
        status_code: 200
        timeout: 5
        verify_ssl: false
  rules:
    - name: Debug event
      condition: event.url_check.status == "up"
      action:
        debug:
          msg: "Application is up and working as expected"

###############################################################################################

    - name: Create incident on ServiceNow and run diagnostics
      condition: event.url_check.status == "down"
      action:
        run_job_template:
          name: nginx_diagnostics
          organization: Default
          post_events: true
          job_args:
            extra_vars:
              short_description: "{{ event.url_check.url.split('://')[1].split('/')[0] }} is down"
              description: "{{ event.url_check.url.split('://')[1].split('/')[0] }} is down - EDA will run diagnostics }}"
              impact: 1
              urgency: 1
              target_host: "{{ event.url_check.url.split('://')[1].split('/')[0] }}"

###############################################################################################
#### RULES BELOW WILL BE TRIGGERED ON SECOND RUN (POST_EVENTS:TRUE) IF ANY CONDITIONS MATCH ###

    # Working remediation
    - name: Remediate TLS certificate issue
      condition: >
          event.diagnostics is defined and
          event.diagnostics.nginx_config_error is match(".*cannot load certificate key.*", ignorecase=true)
      action:
        run_workflow_template:
          name: servicenow_auto_remediate_tls-issue_workflow
          organization: Default
          post_events: true
          set_facts: true
          job_args:
            extra_vars:
              incident_sys_id: "{{ event.incident_sys_id }}"
              target_host: "{{ event.target_host }}"
              close_notes: |
                ########################### EDA REMEDIATION STATUS UPDATE ############################

                A TLS certificate verification failure was detected. This may be caused by an
                expired certificate, a self-signed certificate that is not trusted, a missing
                root or intermediate CA, or a mismatch between the certificate and its private key.
                Please verify the certificate chain and ensure the correct key is configured.

                EDA has successfuly remediated. Check job_template
              work_notes: | # on failure
                ########################### EDA REMEDIATION STATUS UPDATE ############################

                A TLS certificate verification failure was detected. This may be caused by an
                expired certificate, a self-signed certificate that is not trusted, a missing
                root or intermediate CA, or a mismatch between the certificate and its private key.
                Please verify the certificate chain and ensure the correct key is configured.

                EDA has not been successful in the attempted remediation. Please investigate.


    # Remediation will fail
    - name: Remediate nginx config error
      condition: >
          event.diagnostics is defined and
          event.diagnostics.nginx_config_error is match(".*unknown directive.*", ignorecase=true)
      action:
        debug:
          msg: >
            The nginx configuration file contains an unknown directive, which indicates
            a potential typo or unsupported instruction. Please verify the config for
            syntax issues or misconfigured modules.

            Attempting auto remediation...

    # Remediation will fail
    - name: Not a known issue - update service now
      condition: event.diagnostics is defined # defined but no known match for existing issue
      action:
        debug:
          msg: >
            The nginx configuration file contains an unknown directive, which indicates
            a potential typo or unsupported instruction. Please verify the config for
            syntax issues or misconfigured modules.

            Attempting auto remediation...

###############################################################################################
#### RULES BELOW WILL BE TRIGGERED ON THIRD RUN (POST_EVENTS:TRUE) to resolve or update incident ###

    # Remediation will fail
    # - name: Resolve or update incident
    #   condition: event.enriched_event.incident_sys_id is defined
    #   action:
    #     debug:
    #       msg: >
    #         A TLS certificate verification failure was detected. This may be caused by an
    #         expired certificate, a self-signed certificate that is not trusted, a missing
    #         root or intermediate CA, or a mismatch between the certificate and its private key.
    #         Please verify the certificate chain and ensure the correct key is configured.

    #         EDA has successfuly remediated. Check job_template

    #         "{{ ansible_eda.event }}"
    #         "{{ ansible_eda.facts }}"
